### ISSUE TITLE
Couldn't Connect to Action Service error 

### ISSUE THREAD

**Issue by LeticiaEsparza** [looker/actions#184]
Customer is seeing this error message rendered in the Actions page. Refreshing in the Actions page resolves the error within the Actions page itself. However, they were still not seeing the Actions available to schedule with in the schedule modal. 

![actions error](https://user-images.githubusercontent.com/32855798/43225116-36645fa6-900d-11e8-8eed-199a1f43228a.png)

**Comment by wilg** [comment]
What version of Looker?

**Comment by LeticiaEsparza** [comment]
5.14.12

**Comment by phillipperalez** [comment]
Closing because issue was solved in Looker
