### ISSUE TITLE
[Slack] Cannot see any channels even with `channels:read`

### ISSUE THREAD

**Issue by lane2day** [looker/actions#226]
Is anyone aware of a bug that prevents you from being able to see any channels and you can only see users in your workspace?
![image](https://user-images.githubusercontent.com/35228145/49559149-cca9b380-f8db-11e8-86d2-de8eaaa619e8.png)

**Comment by patrickjdwyer** [comment]
+1 for this, noticed today when I tried to use the Slack integration

**Comment by snarron** [comment]
+1 Another trial customer in Japan

**Comment by kayelow** [comment]
+1 stakeholder would _love_ a specific viz sent to a channel every morning

**Comment by animcdowell** [comment]
For the Slack Attachment action, the bot user needs to be added to the public channel before the channel will be visible in the list.
