### ISSUE TITLE
[slack] Cannot see private channels

### ISSUE THREAD

**Issue by ravimody** [looker/actions#227]
I added the bot to a private channel but it doesn't give an option to send results to that channel. It can successfully send to any user and to public channels its added to. I gave it these three permissions:

- channels:read
- users:read
- files:write:user

Do I need to give it more permissions to enable sends to private channels?

**Comment by gwaldmantoast** [comment]
+1

**Comment by sumeshnmenon** [comment]
+1

**Comment by wilg** [comment]
Looks like this is not currently supported. The relevant permission is [`groups:read`](https://api.slack.com/scopes/groups:read), but currently the Slack action does not attempt to list groups.

We definitely want to address this. Thanks for the reports!

**Comment by mghita-guardian** [comment]
+1
